//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDSAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAttendance
    {
        public int ID { get; set; }
        public Nullable<double> EnrollNo { get; set; }
        public Nullable<int> Inout { get; set; }
        public Nullable<int> VerifyMode { get; set; }
        public string DeviceIP { get; set; }
        public string DeviceLocation { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<int> EmpID { get; set; }
    }
}
