//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDSAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int ID { get; set; }
        public Nullable<double> EnrollNo { get; set; }
        public string EnrollName { get; set; }
        public string ShiftName { get; set; }
        public Nullable<System.DateTime> ShiftStart { get; set; }
        public Nullable<System.DateTime> ShiftEnd { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> LocalID { get; set; }
        public Nullable<System.DateTime> MinShiftStart { get; set; }
        public Nullable<System.DateTime> MaxShiftStart { get; set; }
        public Nullable<System.DateTime> MinShiftEnd { get; set; }
        public Nullable<System.DateTime> MaxShiftEnd { get; set; }
        public Nullable<int> ShiftDayChange { get; set; }
        public Nullable<System.DateTime> RegisteredOn { get; set; }
    }
}
