//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDSAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int ID { get; set; }
        public string LeaveType { get; set; }
        public Nullable<double> EnrollNo { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
    }
}
